spring:
  application:
    name: service_indexer

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign.client.config.default.connectTimeout: 160000000
feign.client.config.default.readTimeout: 160000000
